spring:
  #postgresql配置
  datasource:
    url: jdbc:postgresql://localhost:5432/nail_db?currentSchema=user_sch
    username: root
    password: 123456
    driverClassName: org.postgresql.Driver


  data:
    #redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      #    password: 123456 #默认为空
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 0     # 最小空闲连接，默认0

    #neo4j配置
    neo4j:
      database: neo4j

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678





  #邮箱基本配置
  mail:
    protocol: smtp
    host: smtp.qq.com
    #端口号465或587
    port: 587
    #发送邮箱
    username: no_reply_nail@qq.com
    nickname: 钉位社区
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: evgjcqhgrbykbcab
    default-encoding: UTF-8
    test-connection: true
    properties:
      mail:
        smtp:
          # 表示SMTP发送邮件，需要进行身份验证
          auth: true
          starttls:
            enable: true
            required: true


jwt:
  alg: dd
  iss: auth0&nail
  key: past35-net07-sun35
  # 1h
  a-ttl: 3600000
  # 15d
  r-ttl: 1296000000
  delay: 0





